entitytypes:
  bat: 1.0
  blaze: 1.0
  cat: 1.0
  chicken: 1.0
  cow: 1.0
  creeper: 1.0
  dolphin: 1.0
  donkey: 1.0
  drowned: 1.0
  enderman: 1.0
  fox: 1.0
  ghast: 1.0
  guardian: 1.0
  hoglin: 1.0
  horse: 1.0
  husk: 1.0
  llama: 1.0
  magma_cube: 1.0
  ocelot: 1.0
  panda: 1.0
  parrot: 1.0
  pig: 1.0
  piglin: 1.0
  pillager: 1.0
  rabbit: 1.0
  sheep: 1.0
  skeleton: 1.0
  slime: 1.0
  spider: 1.0
  squid: 1.0
  turtle: 1.0
  witch: 1.0
  wither_skeleton: 1.0
  zombie: 1.0
  zombified_piglin: 1.0